spring.application.name=human-resources-payroll
server.port=8101

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Resilience4j
spring.cloud.circuitbreaker.resilience4j.enabled=true
resilience4j.circuitbreaker.instances.paymentServiceCircuit.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentServiceCircuit.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentServiceCircuit.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.paymentServiceCircuit.slidingWindowSize=100
resilience4j.circuitbreaker.instances.paymentServiceCircuit.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.paymentServiceCircuit.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentServiceCircuit.eventConsumerBufferSize=10

spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.client.name=human-resources-worker
feign.hystrix.enabled=false
spring.cloud.loadbalancer.enabled=true
spring.cloud.discovery.client.simple.enabled=true  # Habilita o cliente de descoberta de serviços

spring.cloud.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.max-attempts=3  # Número de tentativas
spring.cloud.loadbalancer.retry.initial-interval=1000  # Intervalo entre tentativas (1 segundo)
spring.cloud.loadbalancer.retry.max-interval=5000
spring.cloud.loadbalancer.retry.backoff-multiplier=2  # Aumento progressivo no tempo de intervalo


spring.cloud.loadbalancer.strategy=random
